<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>2afd7b6c-a688-4f78-bc9c-402cc1b4278a</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.4" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.1.4" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\Modules\Signup\Signup-Application\Signup-Application.csproj" />
    <ProjectReference Include="..\Modules\Signup\Signup-Infrastructure\Signup-Infrastructure.csproj" />
  </ItemGroup>

</Project>
