// <auto-generated />
using System;
using Assignment_Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment_Domain.Migrations
{
    [DbContext(typeof(AssignmentDbContext))]
    [Migration("20260514114053_newMigration")]
    partial class newMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Danish_Norwegian_CI_AS")
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assignment_Domain.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignmentSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nchar(500)")
                        .IsFixedLength();

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("AssignmentSetId");

                    b.ToTable("Assignment", (string)null);
                });

            modelBuilder.Entity("Assignment_Domain.Entities.AssignmentExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("SnapshotTakenAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SourceExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.ToTable("AssignmentExercise", (string)null);
                });

            modelBuilder.Entity("Assignment_Domain.Entities.AssignmentFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<bool?>("SelfEvaluationSubmitted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SubmittedAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedAssignmentId");

                    b.ToTable("AssignmentFeedback", (string)null);
                });

            modelBuilder.Entity("Assignment_Domain.Entities.AssignmentQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignmentExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SourceQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentExerciseId");

                    b.ToTable("AssignmentQuestion", (string)null);
                });

            modelBuilder.Entity("Assignment_Domain.Entities.AssignmentSet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nchar(500)")
                        .IsFixedLength();

                    b.Property<Guid?>("GradesheetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("GradingPublished")
                        .HasColumnType("bit");

                    b.Property<bool?>("Inactive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPublihsed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("AssignmentSet", (string)null);
                });

            modelBuilder.Entity("Assignment_Domain.Entities.ErrorType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nchar(1000)")
                        .IsFixedLength();

                    b.Property<string>("ErrorName")
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .IsFixedLength();

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("ErrorType", (string)null);
                });

            modelBuilder.Entity("Assignment_Domain.Entities.ExerciseFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ErrorType")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Feedbacktext")
                        .HasMaxLength(1000)
                        .HasColumnType("nchar(1000)")
                        .IsFixedLength();

                    b.Property<int?>("PointsGiven")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("SubmittedExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ErrorType");

                    b.HasIndex("SubmittedExerciseId");

                    b.ToTable("ExerciseFeedback", (string)null);
                });

            modelBuilder.Entity("Assignment_Domain.Entities.GradeSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignmentSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentSetId");

                    b.ToTable("GradeSheet", (string)null);
                });

            modelBuilder.Entity("Assignment_Domain.Entities.SelfEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Points")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("SubmittedExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedExerciseId");

                    b.ToTable("SelfEvaluation", (string)null);
                });

            modelBuilder.Entity("Assignment_Domain.Entities.SubmittedAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<bool?>("SelfEvaluationSubmitted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.ToTable("SubmittedAssignment", (string)null);
                });

            modelBuilder.Entity("Assignment_Domain.Entities.SubmittedExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FeedbackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("SubmittedAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedAssignmentId");

                    b.ToTable("SubmittedExercise", (string)null);
                });

            modelBuilder.Entity("Assignment_Domain.Entities.Assignment", b =>
                {
                    b.HasOne("Assignment_Domain.Entities.AssignmentSet", "AssignmentSet")
                        .WithMany("Assignments")
                        .HasForeignKey("AssignmentSetId")
                        .HasConstraintName("FK_Assignment_AssignmentSet");

                    b.Navigation("AssignmentSet");
                });

            modelBuilder.Entity("Assignment_Domain.Entities.AssignmentExercise", b =>
                {
                    b.HasOne("Assignment_Domain.Entities.Assignment", "Assignment")
                        .WithMany("AssignmentExercises")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AssignmentExercise_Assignment");

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("Assignment_Domain.Entities.AssignmentFeedback", b =>
                {
                    b.HasOne("Assignment_Domain.Entities.SubmittedAssignment", "SubmittedAssignment")
                        .WithMany("AssignmentFeedbacks")
                        .HasForeignKey("SubmittedAssignmentId")
                        .HasConstraintName("FK_AssignmentFeedback_SubmittedAssignment");

                    b.Navigation("SubmittedAssignment");
                });

            modelBuilder.Entity("Assignment_Domain.Entities.AssignmentQuestion", b =>
                {
                    b.HasOne("Assignment_Domain.Entities.AssignmentExercise", null)
                        .WithMany("Questions")
                        .HasForeignKey("AssignmentExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Assignment_Domain.Entities.ExerciseFeedback", b =>
                {
                    b.HasOne("Assignment_Domain.Entities.ErrorType", "ErrorTypeNavigation")
                        .WithMany("ExerciseFeedbacks")
                        .HasForeignKey("ErrorType")
                        .HasConstraintName("FK_ExerciseFeedback_ErrorType");

                    b.HasOne("Assignment_Domain.Entities.SubmittedExercise", "SubmittedExercise")
                        .WithMany("ExerciseFeedbacks")
                        .HasForeignKey("SubmittedExerciseId")
                        .HasConstraintName("FK_ExerciseFeedback_SubmittedExercise");

                    b.Navigation("ErrorTypeNavigation");

                    b.Navigation("SubmittedExercise");
                });

            modelBuilder.Entity("Assignment_Domain.Entities.GradeSheet", b =>
                {
                    b.HasOne("Assignment_Domain.Entities.AssignmentSet", "AssignmentSet")
                        .WithMany("GradeSheets")
                        .HasForeignKey("AssignmentSetId")
                        .HasConstraintName("FK_GradeSheet_AssignmentSet");

                    b.Navigation("AssignmentSet");
                });

            modelBuilder.Entity("Assignment_Domain.Entities.SelfEvaluation", b =>
                {
                    b.HasOne("Assignment_Domain.Entities.SubmittedExercise", "SubmittedExercise")
                        .WithMany("SelfEvaluations")
                        .HasForeignKey("SubmittedExerciseId")
                        .HasConstraintName("FK_SelfEvaluation_SubmittedExercise");

                    b.Navigation("SubmittedExercise");
                });

            modelBuilder.Entity("Assignment_Domain.Entities.SubmittedAssignment", b =>
                {
                    b.HasOne("Assignment_Domain.Entities.Assignment", "Assignment")
                        .WithMany("SubmittedAssignments")
                        .HasForeignKey("AssignmentId")
                        .HasConstraintName("FK_SubmittedAssignment_Assignment");

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("Assignment_Domain.Entities.SubmittedExercise", b =>
                {
                    b.HasOne("Assignment_Domain.Entities.SubmittedAssignment", "SubmittedAssignment")
                        .WithMany("SubmittedExercises")
                        .HasForeignKey("SubmittedAssignmentId")
                        .HasConstraintName("FK_SubmittedExercise_SubmittedAssignment");

                    b.Navigation("SubmittedAssignment");
                });

            modelBuilder.Entity("Assignment_Domain.Entities.Assignment", b =>
                {
                    b.Navigation("AssignmentExercises");

                    b.Navigation("SubmittedAssignments");
                });

            modelBuilder.Entity("Assignment_Domain.Entities.AssignmentExercise", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Assignment_Domain.Entities.AssignmentSet", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("GradeSheets");
                });

            modelBuilder.Entity("Assignment_Domain.Entities.ErrorType", b =>
                {
                    b.Navigation("ExerciseFeedbacks");
                });

            modelBuilder.Entity("Assignment_Domain.Entities.SubmittedAssignment", b =>
                {
                    b.Navigation("AssignmentFeedbacks");

                    b.Navigation("SubmittedExercises");
                });

            modelBuilder.Entity("Assignment_Domain.Entities.SubmittedExercise", b =>
                {
                    b.Navigation("ExerciseFeedbacks");

                    b.Navigation("SelfEvaluations");
                });
#pragma warning restore 612, 618
        }
    }
}
